const request = require('request');
const cheerio = require('cheerio');
const fs = require('fs');
const url = "https://en.dict.naver.com/api3/enko/search?query=";

parser = (text) => new Promise((resolve) => {
    request(url + text, function(error, response, body) {
        var jbody = JSON.parse(body);
        var words = jbody.searchResultMap.searchResultListMap.WORD.items;
        var list = [];
        for (var i = 0; i < words.length; i++) {
            if (words[i].matchType != "exact:entry" && words[i].matchType != "exact:revert") continue;
            var meansCollector = words[i].meansCollector;
            for (var j = 0; j < meansCollector.length; j++) {
                var means = meansCollector[j].means;
                for (var x = 0; x < means.length; x++) {
                    list.push({
                        typeko: meansCollector[j].partOfSpeech,
                        typeen: meansCollector[j].partOfSpeech2,
                        value: means[x].value
                    });
                }
            }
        }
        if (list.length > 0) {
            resolve({
                단어: text,
                뜻: list
            });
        } else {
            console.log("뜻 없는 단어 스킵");
            resolve(null);
        }
    });
});

main = async(text) => {
    var data = "ABDOMEN ABOLISH ACCESSORY ADORE ADVOCACY AERIAL AFTERMATH AGGRAVATE AGGREGATE AGITATE AIDE AIL AIRWAYS AISLE ALBEIT ALGORITHM ALLEGIANCE ALLERGY ALOUD ALTAR ALTITUDE AMBIGUITY AMMUNITION AMNESTY AMPLE AMPLIFY ANALOGY ANALYTIC ANATOMY ANECDOTE ANGLER ANGUISH ANOMALY ANT ANTIBIOTIC ANTIBODY APPARATUS APPENDIX APPETITE APPLAUD APPLAUSE APPLIANCE APPREHEND APPRENTICE APPROPRIATED APT AQUARIUM ARBITRARY ARBITRATE ARC ARCTIC ARTERY ARTILLERY ASCEND ASS ASSIMILATE ASTHMA ASYLUM AUDIBLE AUTHORITARIAN AUTOBIOGRAPHY AUTOMATE AUTONOMOUS AVIATION AWE AXIS BADGE BAIL BAIT BALCONY BALD BANNER BAPTIST BARON BASKETBALL BATCH BATTALION BELOVED BENEFICIARY BETA BEWILDER BILATERAL BINOCULARS BLEAK BLOCKADE BLOSSOM BLOUSE BLUNT BLUSH BOTANY BOURGEOIS BOUT BOWEL BOYCOTT BRACE BRACKET BRIBE BRIGADE BRISK BROCHURE BROW BUCKLE BUD BUFFER BULGE BULLETIN BURGLE BUST BUTCHER BUTT BYPASS CALF CANDY CANE CANNON CAPTIVE CARBOHYDRATE CARDBOARD CARDINAL CASSETTE CATASTROPHE CAUSAL CELLAR CELLULAR CEMENT CERAMIC CEREAL CHALK CHANT CHAP CHARITABLE CHATTER CHEMIST CHERRY CHIMNEY CHORD CHORUS CHUCK CHUCKLE CIGAR CIRCUS CLAMP CLAN CLAP CLASP CLAW CLEANSE CLENCH CLERGY CLOAK CLOWN COARSE COCAINE COCK COCKTAIL COEFFICIENT COERCE COIL COKE COLLISION COMB COMMEMORATE COMMENCE COMMEND COMMONWEALTH COMMUNAL COMMUNISM COMPARTMENT COMPASSION COMPLIMENT COMPOSITE COMPOST COMRADE CONCLUSIVE CONDENSE CONDOM CONE CONFEDERATE CONFIDE CONGEST CONQUER CONSECUTIVE CONSORTIUM CONSPICUOUS CONVENE CONVERGE CONVERSELY CORAL CORPSE COSMETIC COSY COURTYARD COVENANT COWBOY CRAB CRADLE CRAMP CRANE CREEK CREST CRICKET CRIPPLE CROOK CROUCH CRUNCH CRUSADE CUB CUE CULMINATE CUPBOARD CURATOR CURB CUSHION CYLINDER DAIRY DALE DANGLE DART DAUNT DAZZLE DEBRIS DECEASED DECREE DEED DEFAULT DEFINITIVE DEGRADE DELETE DELTA DEMISE DEMON DENOUNCE DENTIST DEPENDENCY DEPLETE DEPOT DESCENT DESSERT DETENTION DEVIATE DIAGNOSTIC DICE DIESEL DIFFERENTIAL DIFFUSE DILUTE DINOSAUR DIOCESE DIPLOMACY DISAPPROVE DISARM DISCERN DISCREPANCY DISGRACE DISINTEGRATE DISMANTLE DISMAY DISPENSE DISPOSITION DISSATISFY DISSENT DITCH DIVERGE DIVERSIFY DIVERSION DIVERT DIZZY DODGE DOLE DOMINANCE DOOM DRAPE DRASTIC DREAD DREADFUL DROUGHT DRUNKEN DUB DUBIOUS DUMB DUPLICATE DURABLE DUSK DWARF DYE DYNAMICS EARNEST EARTHQUAKE ECCENTRIC ECLIPSE ECOLOGY ECSTASY EFFICACY ELASTIC ELECTORATE ELF ELICIT ELUSIVE EMBARK EMBED EMBROIDER EMBRYO EMIGRATE EMPOWER ENCOMPASS ENGRAVE ENLIST ENQUIRE ENSEMBLE ENSUE ENTAIL ENZYME EPIC EPIDEMIC EQUILIBRIUM ERASE ERODE EROSION ESCALATE ETERNAL EVANGELICAL EVAPORATE EX EXACERBATE EXPANSE EXPEL EXPIRE EXQUISITE EXTERIOR EXTINCT FABULOUS FACIAL FACTUAL FAREWELL FASTEN FATIGUE FEASIBLE FEAST FEND FESTIVE FIDDLE FILTH FIXTURE FLAKE FLARE FLATS FLATTER FLOP FLUCTUATE FLUTTER FOAM FOIL FOLIAGE FORMIDABLE FORTHCOMING FOUNTAIN FRAGRANT FRANTIC FREIGHT FUME FUNGUS FURY FUSS GARMENT GEL GENERALS GENERATOR GIG GIGGLE GINGER GLAZE GLITTER GLOBE GOOSE GOWN GRAM GRAMMAR GRAPE GRATE GRATITUDE GRIT GROAN GROOM GROVE GROWL GRUNT GUILD GUM GYMNASIUM HACK HAIL HAM HAMBURGER HANDKERCHIEF HARNESS HATRED HAWK HAY HEAVE HEIGHTEN HEMISPHERE HEN HERALD HEROIN HETEROSEXUAL HIGHLAND HIKE HINDER HINGE HISS HOCKEY HOLLY HORRIFIED HOVER HOWL HUM HUMANITARIAN HURDLE HURL ICON ID IGNITE IGNORANCE IMMERSE IMMINENT IMPERATIVE IMPLANT IMPROVISE INCIDENTAL INCUMBENT INCUR INDICT INFERIOR INFLICT INFLUENZA INFUSE INHALE INLAND INMATE INNINGS INNOCENCE INTAKE INTELLIGIBLE INTERCEPT INTERCOURSE INTERMEDIATE INTERROGATE INTERSECT INTESTINE INTRINSIC INTRUDE INVENTORY ION IVORY JEALOUS JEOPARDY JEWEL JOCKEY JOG JOURNALISM JUDICIARY JUNCTION JUNK KIDNEY KNIGHT LAD LADEN LAG LAMENT LANDMARK LAPSE LARVA LASH LATERAL LAVISH LEAFLET LEASH LEGION LESION LETHAL LIAISON LIGHTNING LIME LIMP LINEN LINING LIQUOR LITIGATE LITTER LOGO LOOT LURE LURK LUST MADAM MAGISTRATE MAID MAJESTY MALL MANDATORY MANKIND MANOR MANSION MARATHON MARINES MARITAL MARSH MARSHAL MARTYR MASCULINE MASSACRE MASSAGE MATERNAL MATTRESS MEADOW MEDIAN MEDICATION MEDITATE MEMBRANE MEMO MEMOIR MEMORABLE MENACE MESSENGER MICROPHONE MICROSCOPE MIDST MIGRANT MILITIA MILLENNIUM MILLILITRE MIMIC MINIATURE MINT MISERY MISTRESS MITIGATE MOAN MOB MODEM MOIST MONASTERY MONK MOOR MORALE MORTAR MOSAIC MOSQUITO MOTIF MOULDING MOUND MOUSTACHE MUCUS MUG MULTIMEDIA MULTINATIONAL MUSE MUTATE MUTE MYSTIC NAIVE NATIONALITY NEGLIGENT NEPHEW NICHE NICKNAME NITROGEN NODE NOMINAL NOMINEE NOTIFY NOWADAYS NUCLEUS NUDE NUISANCE NUMB NUMERIC NUN NURTURE NUTRIENT OATH OBSCENE OFFSPRING ONSET OPTIMAL OPTIMISM ORIENT ORNAMENT ORPHAN OUTRIGHT OUTSET OVAL OVERRIDE OVERT OVERTHROW OVERVIEW PA PACT PADDLE PAL PANTS PAPA PAR PARADIGM PARADISE PARALYSE PARASITE PARCEL PARTISAN PASSPORT PASTA PASTE PASTEL PASTORAL PASTRY PASTURE PATHETIC PATRIARCH PEA PEACH PEDAL PEDESTRIAN PENDING PENINSULA PERCH PERFUME PERIL PERSECUTE PERSUASION PEST PESTICIDE PETROLEUM PETTY PHARMACEUTICAL PHYSICIST PICKUP PICNIC PIER PIERCE PIGEON PILLAR PINT PIPELINE PIRATE PISTOL PIVOT PIZZA PLAINS PLANTATION PLASMA PLASTER PLAUSIBLE PLOUGH PLUCK PLUMBING POISE PONDER PONY PORCH PORK POSTURE POTENT POUNDING PRAGMATIC PRECAUTION PRECIPITATE PREMATURE PRESENTLY PRESIDE PROBATION PROCESSION PRONE PROPEL PROPHET PROPRIETOR PROSE PROTOTYPE PROXIMITY PRUDENT PUBLICIZE PUFF PURSE PUTT PYRAMID QUALITATIVE QUANTIFY QUANTUM QUARREL QUARRY QUERY QUEST RADAR RADIOACTIVE RAG RAINBOW RAKE RAMP RANCH RATIFY RATION RATIONALE RECITE RECKLESS RECLAIM RECOLLECT RECTANGLE REDUNDANT REEF REEL REFEREE REFERENDUM REGIMENT REIN RELAY RELENTLESS RELISH RELUCTANCE REMAINDER REMINISCE RENAISSANCE RENOVATE RENOWN REPLICATE REPRODUCTIVE REQUISITE RESERVOIR RESURRECT RETALIATE RETENTION RETROSPECT REUNION REVENGE REVERE REVOLT REVOLVE RIBBON RIG RIM RINSE RIPE RIPPLE RITE ROAM ROBE ROBUST ROVE RUMBLE RUNWAY RUST RUTHLESS SACKS SADDLE SALON SALUTE SALVATION SANCTUARY SATURATE SCARF SCOOP SCRIPTURE SCRUB SEAM SEASONING SEDIMENT SEDUCE SEGREGATE SEMANTIC SENSOR SERIAL SERMON SERUM SEVER SEWAGE SHARK SHEPHERD SHORTS SHRED SHRIMP SHRINE SHRUB SHUDDER SHUFFLE SHUTTLE SIBLING SIEGE SIGNIFY SILICON SIMMER SIMPLICITY SINGULAR SKATE SKELETON SLAB SLACK SLASH SLATE SLAUGHTER SLENDER SLICK SLOGAN SMACK SMEAR SMUGGLE SNACK SNEAK SNIFF SOB SOBER SOCIALISE SOCIALISM SOCKET SOFA SOLEMN SOLICITOR SOLIDARITY SOLITARY SOOTHE SORROW SOUR SOW SPA SPAWN SPEAR SPECTATOR SPIDER SPIRAL SPITE SPLENDID SPRAWL SPRINKLE SPRINT SPROUT SQUASH SQUAT STAIRCASE STALK STARK STATIC STEPMOTHER STEREO STERILE STERLING STEWARD STICKY STINK STOCKING STOOL STOVE STRAY STRIVE STUBBORN STUD STUMP SUBMARINE SUBMISSION SUBSTANTIVE SULPHUR SUPERFICIAL SUPERINTENDENT SURF SURGICAL SURVEILLANCE SUSCEPTIBLE SWAMP SWAP SWAY SWEATER SWIRL SYMMETRY SYMPHONY SYNTHETIC TABLET TABLOID TACK TAILOR TAME TAN TANGIBLE TARIFF TECHNICIAN TEE TEEN TELEGRAPH TEMPER TEMPERAMENT TEMPORAL TENTATIVE TENURE TERRAIN TERRIFIC TESTIFY THEOLOGICAL THERAPEUTIC THEREAFTER THERMAL THRONE THUMP TIDY TODDLE TOKEN TOLERANCE TOLERANT TOLL TOMB TORCH TORMENT TOW TRACT TRACTOR TRAILER TRANQUIL TRANSCEND TRANSIT TRANSPARENT TREAD TRENCH TRICKLE TRIO TRIPLE TRIVIAL TROT TROUT TRUMPET TUB TURBULENCE TURF TURTLE TWITCH TYPED ULCER UMBRELLA UN UNANIMOUS UNDERESTIMATE UNDERGRADUATE UNDERLINE UPHOLD UPRIGHT URINE USAGE USHER UTTERLY VACANT VACATION VACCINE VACUUM VALVE VASE VEGETARIAN VEGETATION VELOCITY VELVET VENT VENTILATE VERB VERGE VERSATILE VEST VETO VICIOUS VIGIL VINE VINEGAR VINTAGE VIOLIN VISA VOCABULARY VOID VOLATILE VOLT VOUCHER VOW VOYAGE WAIL WALLET WARDROBE WARFARE WARY WEDGE WEE WELD WHATSOEVER WHEAT WHEREBY WHISK WHOLESALE WILDERNESS WINDING WINK WIRELESS WITCH WITHHOLD WIZARD WORTHWHILE WRESTLE WRINKLE YACHT ZIP ZOO  ";
    data = data.split(' ');
    var list = [];
    for (var i = 0; i < data.length; i++) {
        if (data[i] == "") continue;
        var dat = await parser(data[i]);
        if (dat == null) continue;
        list.push(dat);
        console.log(i + "/" + (data.length - 1));
    }
    fs.writeFileSync('output.json', JSON.stringify(list).replace(/(<([^>]+)>)/ig, ""));
}

main();